// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BarOfType: typeof import("./src/components/barOfType.vue")["default"];
    BaroOfType: typeof import("./src/components/baroOfType.vue")["default"];
    Error: typeof import("./src/components/error.vue")["default"];
    ErrorPage: typeof import("./src/components/errorPage.vue")["default"];
    HorizontalScroll: typeof import("./src/components/horizontalScroll.vue")["default"];
    IconCommunity: typeof import("./src/components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./src/components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./src/components/icons/IconEcosystem.vue")["default"];
    IconSupport: typeof import("./src/components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./src/components/icons/IconTooling.vue")["default"];
    Loading: typeof import("./src/components/Loading.vue")["default"];
    LoadingPage: typeof import("./src/components/loadingPage.vue")["default"];
    PullRefresh: typeof import("./src/components/pullRefresh.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TabBar: typeof import("./src/components/tabBar.vue")["default"];
    TabBarOfType: typeof import("./src/components/tabBarOfType.vue")["default"];
    VanButton: typeof import("vant/es")["Button"];
    VanIcon: typeof import("vant/es")["Icon"];
    VanImage: typeof import("vant/es")["Image"];
    VanLoading: typeof import("vant/es")["Loading"];
    VanPullRefresh: typeof import("vant/es")["PullRefresh"];
    VanTab: typeof import("vant/es")["Tab"];
    VanTabs: typeof import("vant/es")["Tabs"];
  }
}
